### ISSUE TITLE
Run a file.prc with the command (when the person execute py index.py)

### ISSUE THREAD

**Issue by Rix565** [Program132/PRC#3]
Vous définissez très clairement le fichier à exécuter dans le fichier index.py.
Mais on pourrait changer cela et rendre ça encore plus pratique, laissez moi vous expliquez...
On pourrait tout simplement définir le fichier à exécuter dans la commande pour démarrer PRC !
Ex :
python3 index.py main.prc

**Comment by Program132** [comment]
Superbe idée mais pour le moment je ne me ferai mais je me renseignerai

**Comment by megat69** [comment]
Je l'ai fait.
Regarde tes pull requests [juste là](https://github.com/Program132/PRC/pull/4)
